import {
  AlertTriangle,
  ArrowRight,
  ChevronDown,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image as ImageIcon,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  X,
  Search,
  BookOpenText,
  LucideIcon,
  GithubIcon as Github,
  MoreHorizontal,
  Equal,
  Copy,
  Check as CheckIcon,
  BookCheck,
  LibrarySquare,
  Link,
  FolderClosed,
  FolderOpen,
} from "lucide-react";
import Image from "next/image";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  gitHub: Github,
  twitter: X,
  check: Check,
  orderbook: BookOpenText,
  more: MoreHorizontal,
  equal: Equal,
  image: ImageIcon,
  copy: Copy,
  checkIcon: CheckIcon,
  chevronDown: ChevronDown,
  book: BookCheck,
  library: LibrarySquare,
  link: Link,
  folder: FolderClosed,
  folderOpen: FolderOpen,
};
